# Generated by Django 6.0.7 on 2026-08-12 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('institucion', models.CharField(max_length=150)),
                ('estado', models.CharField(max_length=50)),
                ('año', models.PositiveIntegerField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formaciones', to='usuarios1.usuario')),
            ],
        ),
    ]
